name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    env:
      ENV_NAME: desenvolvimento
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        run: echo "Setting up environment: ${{ env.ENV_NAME }}"
      - name: Run a one-line script
        run: echo "Hello, world! Environment: ${{ env.ENV_NAME }}"
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project. Environment: ${{ env.ENV_NAME }}"
