name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: Development

    steps:
      - uses: actions/checkout@v3

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} 
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore path/TR.Azure.Api/TR.Azure.Api.sln

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish --no-restore --no-build --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish
