name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} 
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore TR.Azure.Api.sln

      - name: Build
        run: dotnet build TR.Azure.Api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish TR.Azure.Api/TR.Azure.Api.csproj --configuration Release --no-restore --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

  deploy:
    needs: build
    environment: desenvolvimento
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./publish

      # AZURE_CREDENTIALS não está criado
      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # REGISTRY_USERNAME e REGISTRY_PASSWORD não está criado
      # - uses: azure/docker-login@v1
      #   with:
      #     login-server: contoso.azurecr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}